# EC2 Instance Configuration
# Generated by connect_existing.sh on Wed Oct 29 10:20:06 +08 2025

export EC2_INSTANCE_ID=""
export EC2_PUBLIC_IP="35.78.78.6"
export EC2_REGION=""
export EC2_KEY_PATH="/Users/wjs/.ssh/trisure_key.pem"
export EC2_SSH_USER="ubuntu"

# SSH command
alias ssh-ec2="ssh -i $EC2_KEY_PATH $EC2_SSH_USER@$EC2_PUBLIC_IP"
