# EC2 Instance Configuration
# Generated by connect_existing.sh on Wed Nov  5 15:19:48 +08 2025

export EC2_INSTANCE_ID=""
export EC2_PUBLIC_IP="3.112.123.115"
export EC2_REGION=""
export EC2_KEY_PATH="/Users/wjs/.ssh/tokyo_private.pem"
export EC2_SSH_USER="ubuntu"

# SSH command
alias ssh-ec2="ssh -i $EC2_KEY_PATH $EC2_SSH_USER@$EC2_PUBLIC_IP"
